name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"
jobs:
  update-sanity:
    runs-on: ubuntu-22.04
    name: Update sanity
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update sanity
        run: yarn add sanity@latest # Not problematic as only a PR gets created
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "[CI] Upgrade sanity to the newest version"
          labels: CI
          branch: sanity-update
          base: main
          commit-message: "[CI] Upgrade sanity"
          delete-branch: true
